# List of creative rejection reasons
rejection_reasons = [
    "This feels like something Future Me would yell at Present Me for agreeing to.",
    "I'm trying to be more honest with myself, so... no.",
    "I'd rather not and say I did. But I won't even say I did.",
    "My schedule is already full of things I'm trying to get out of.",
    "I'm saving my energy for a future crisis I'll inevitably create myself.",
    "That sounds like a problem for someone who isn't me.",
    "I'm currently booked with regrets from saying yes to similar requests.",
    "I've reached my quota of poor decisions for this week.",
    "My gut says no, and my therapist says I should listen to my gut more.",
    "I'm currently in a committed relationship with my couch.",
    "That would conflict with my very important plans of doing absolutely nothing.",
    "I'm allergic to commitments that don't spark joy.",
    "I'm on a strict diet of saying no to things that stress me out.",
    "I've consulted with my future self, and they advised against it.",
    "My magic 8-ball says 'outlook not so good'.",
    "I'm currently at capacity for pretending to be interested in new projects.",
    "That sounds like a wonderful opportunity for someone else.",
    "I'm currently in a season of saying no to things that aren't ice cream.",
    "I'm practicing the art of disappointing people upfront rather than later.",
    "My schedule is already double-booked with existential crises.",
    "I'd love to, but I'm currently booked for a staring contest with my ceiling.",
    "That sounds amazing! For someone with significantly fewer regrets than me.",
    "I'm currently in a deep committed relationship with my peace of mind.",
    "My calendar says yes, but my mental health says absolutely not.",
    "I'm currently at my maximum capacity for potential disappointments.",
    "That's going to conflict with my strict schedule of avoiding unnecessary stress.",
    "I'd have to consult with my house plants, and they're notoriously picky about my availability.",
    "I'm currently saving all my enthusiasm for pretending to enjoy mandatory office functions.",
    "I've already allocated all my decision-making energy to choosing what to watch tonight.",
    "That sounds wonderful, but I'm practicing setting boundaries with people I actually like.",
    "I'm currently in a self-improvement phase called 'not doing things I'll resent later'.",
    "My life coach advised me to avoid anything requiring pants and social energy in the same day.",
    "I'm fully booked with back-to-back sessions of procrastinating on things I've already committed to.",
    "According to my personal risk assessment, that has a high probability of becoming a story I tell my therapist.",
    "I've exceeded my monthly quota of pretending to be a functioning adult.",
    "I would, but I'm busy cultivating my reputation as someone who values their free time.",
    "That conflicts with my ongoing project of disappointing fewer people by committing to less.",
    "My future self just called and specifically asked me not to do that.",
    "I'm currently focusing on activities that don't make me question my life choices.",
    "I'm following a strict regimen of only saying yes to things that come with naps.",
    "I've recently implemented a 'no new mistakes' policy, and that sounds like a violation.",
    "That sounds perfect for somebody who hasn't already reached their lifetime quota of uncomfortable situations.",
    "I'm saving my social battery for an emergency, like being forced to attend a distant relative's wedding.",
    "I'm currently honoring my commitment to my past self to stop overcommitting.",
    "That would interfere with my carefully cultivated schedule of avoiding responsibilities.",
    "My personal board of directors (me, myself, and I) has unanimously voted against it.",
    "I'm currently in a complex relationship with reality, and adding that to the mix would just complicate things.",
    "I've recently taken a vow to only participate in activities that won't end up as cautionary tales.",
    "I'm too busy practicing the ancient art of not making my life unnecessarily complicated.",
    "According to my life syllabus, I'm currently focused on the chapter titled 'Learning When to Say No'.",
    "I've reached my monthly limit of pretending to be excited about things I'll inevitably regret.",
    "That sounds like something I'd need at least three personality upgrades to handle.",
    "My emotional bandwidth is currently being used to stream 'Avoiding Responsibility: Season 5'.",
    "I just checked with my inner child, and they're throwing a tantrum at the mere suggestion.",
    "My fortune cookie explicitly warned me against saying yes to things that sound suspiciously like work.",
    "I'm currently booked for an extensive study on how long I can avoid making new commitments.",
    "That would interfere with my rigorous schedule of second-guessing previous decisions.",
    "I've recently subscribed to a lifestyle called 'Not Today, Maybe Never' and I'm really committed to it.",
    "My anxiety has anxiety about that suggestion.",
    "I'm currently in the middle of a long-term project called 'Reclaiming My Free Time'.",
    "I'd love to, but my cat says I've been too social lately and it's affecting our relationship.",
    "That conflicts with my spiritual practice of avoiding situations that require a fake smile.",
    "I'm currently at capacity for things that will keep me awake at 3 AM with regret.",
    "I've recently taken a vow to only say yes to things that don't make my future self want to time travel and slap me.",
    "According to my personal oracle (Magic 8-Ball), all signs point to 'Who do you think you're kidding?'",
    "I'm currently following a strict regimen of only doing things that have a low probability of becoming anecdotes in therapy.",
    "That would violate my doctor's orders to avoid situations that make me question humanity.",
    "I'm saving all my yes's for emergencies, like free food or puppy cuddles.",
    "My professional decision-maker (also me, just wearing glasses) strongly advises against it.",
    "I've temporarily suspended my participation in activities that can't be done in sweatpants.",
    "I'm currently in a committed relationship with my boundaries, and they're the jealous type.",
    "That would conflict with my upcoming TED Talk: 'The Art of Avoiding Things You Don't Want To Do'.",
    "I'm observing a personal holiday called 'Not Getting Involved Day' which, coincidentally, occurs whenever I'm asked to do something.",
    "I've reached my lifetime quota of saying yes to things that sound simple but inevitably become complicated.",
    "My schedule is currently full of imaginary appointments I created specifically to avoid real ones.",
    "According to my personal constitution, I'm legally bound to reject any proposal that doesn't include snacks.",
    "I'm currently focusing on activities with a return-on-investment for my mental health, and that doesn't qualify.",
    "My enthusiasm coordinator (also me) has evaluated your request and regrets to inform you that we're all out of enthusiasm.",
    "I'm currently at my maximum capacity for potential stories that begin with 'I don't know why I agreed to this...'",
    "That sounds like the kind of thing my biographer would describe as 'the beginning of the end'.",
    "I'm currently following the advice of my future self who time-traveled specifically to warn me about saying yes to that.",
    "I've implemented a new policy of only saying yes to things that won't make me question my life choices in the middle of doing them.",
    "My decision-making department is closed for renovations indefinitely.",
    "That would violate my personal oath to stop collecting regrettable experiences.",
    "I'm currently booked for an intensive course in 'Learning From Past Mistakes 101'.",
    "According to my hierarchy of needs, saying no to that ranks higher than saying yes.",
    "I've promised my therapist I'd stop creating new content for our sessions.",
    "I'm observing a strict policy of only accepting invitations that come with an escape plan.",
    "My availability for that falls somewhere between 'when pigs fly' and 'the twelfth of never'.",
    "I've recently outsourced all my decision-making to a Magic 8-Ball, and it just keeps saying 'Don't count on it'.",
    "I've reached my monthly limit of pretending to be excited about things I'll inevitably regret.",
    "That sounds like something I'd need at least three personality upgrades to handle.",
    "My emotional bandwidth is currently being used to stream 'Avoiding Responsibility: Season 5'.",
    "I just checked with my inner child, and they're throwing a tantrum at the mere suggestion.",
    "My fortune cookie explicitly warned me against saying yes to things that sound suspiciously like work.",
    "I'm currently booked for an extensive study on how long I can avoid making new commitments.",
    "That would interfere with my rigorous schedule of second-guessing previous decisions.",
    "I've recently subscribed to a lifestyle called 'Not Today, Maybe Never' and I'm really committed to it.",
    "My anxiety has anxiety about that suggestion.",
    "I'm currently in the middle of a long-term project called 'Reclaiming My Free Time'.",
    "I'd love to, but my cat says I've been too social lately and it's affecting our relationship.",
    "That conflicts with my spiritual practice of avoiding situations that require a fake smile.",
    "I'm currently at capacity for things that will keep me awake at 3 AM with regret.",
    "I've recently taken a vow to only say yes to things that don't make my future self want to time travel and slap me.",
    "According to my personal oracle (Magic 8-Ball), all signs point to 'Who do you think you're kidding?'",
    "I'm currently following a strict regimen of only doing things that have a low probability of becoming anecdotes in therapy.",
    "That would violate my doctor's orders to avoid situations that make me question humanity.",
    "I'm saving all my yes's for emergencies, like free food or puppy cuddles.",
    "My professional decision-maker (also me, just wearing glasses) strongly advises against it.",
    "I've temporarily suspended my participation in activities that can't be done in sweatpants.",
    "I'm currently in a committed relationship with my boundaries, and they're the jealous type.",
    "That would conflict with my upcoming TED Talk: 'The Art of Avoiding Things You Don't Want To Do'.",
    "I'm observing a personal holiday called 'Not Getting Involved Day' which, coincidentally, occurs whenever I'm asked to do something.",
    "I've reached my lifetime quota of saying yes to things that sound simple but inevitably become complicated.",
    "My schedule is currently full of imaginary appointments I created specifically to avoid real ones.",
    "According to my personal constitution, I'm legally bound to reject any proposal that doesn't include snacks.",
    "I'm currently focusing on activities with a return-on-investment for my mental health, and that doesn't qualify.",
    "My enthusiasm coordinator (also me) has evaluated your request and regrets to inform you that we're all out of enthusiasm.",
    "I'm currently at my maximum capacity for potential stories that begin with 'I don't know why I agreed to this...'",
    "That sounds like the kind of thing my biographer would describe as 'the beginning of the end'.",
    "I'm currently following the advice of my future self who time-traveled specifically to warn me about saying yes to that.",
    "I've implemented a new policy of only saying yes to things that won't make me question my life choices in the middle of doing them.",
    "My decision-making department is closed for renovations indefinitely.",
    "That would violate my personal oath to stop collecting regrettable experiences.",
    "I'm currently booked for an intensive course in 'Learning From Past Mistakes 101'.",
    "According to my hierarchy of needs, saying no to that ranks higher than saying yes.",
    "I've promised my therapist I'd stop creating new content for our sessions.",
    "I'm observing a strict policy of only accepting invitations that come with an escape plan.",
    "My availability for that falls somewhere between 'when pigs fly' and 'the twelfth of never'.",
    "I've recently outsourced all my decision-making to a Magic 8-Ball, and it just keeps saying 'Don't count on it'."
]